version: '3'
services:
  www:
    image: ukid/v2board:master
    volumes:
      - './www:/www'
      - './wwwlogs:/wwwlogs'
      - './caddy.conf:/run/caddy/caddy.conf'
      - './supervisord.conf:/run/supervisor/supervisord.conf'
      - './crontabs.conf:/etc/crontabs/root'
      - './.caddy:/root/.caddy'
    ports:
      - '80:80'
      - '443:443'
    restart: always
    networks:
      - v2board_net

  mysql:
    image: mysql:5.7.29
    volumes:
      - './mysql:/var/lib/mysql'
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: v2boardisbest
      MYSQL_DATABASE: v2board
    networks:
      - v2board_net

networks:
   v2board_net: